// https://beta.nextjs.org/docs/api-reference/file-conventions/head
// 최신버전에서는 Head가 아니라 metadata라는 것을 사용함
export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
